name: compiler_dart
description: "ðŸ­ Dart-Compiler for the Candy language"
version: 0.0.1
homepage: https://github.com/JonasWanke/candy

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.6.0
  basics: ^0.4.0
  code_builder: ^3.4.1
  collection: ^1.14.12
  compiler:
    path: ../compiler
  dartx: ^0.5.0
  extra_pedantic: ^1.2.0
  freezed_annotation: ^0.11.0+1
  json_serializable: ^3.4.1
  meta: ^1.1.8
  yaml_edit:
    git:
      url: https://github.com/google/dart-neats.git
      ref: ad4991aaeb66b7df20e4746b9dc79346266366b1
      path: yaml_edit

dev_dependencies:
  build_runner: ^1.10.1
  freezed: ^0.11.5
  json_serializable_generator: ^1.0.1
  test: ^1.14.3
