name: lsp_server
description: "ðŸ­ LSP server for the Candy language"
version: 0.0.1
homepage: https://github.com/JonasWanke/candy

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^0.39.5
  analyzer_plugin: ^0.3.0
  args: ^1.6.0
  async: ^2.4.2
  basics: ^0.4.0
  collection: ^1.14.12
  compiler:
    path: ../compiler
  compiler_dart:
    path: ../compiler_dart
  extra_pedantic: ^1.2.0
  freezed_annotation: ^0.12.0
  meta: ^1.1.8
  parser:
    path: ../parser
  pedantic: ^1.9.2
  petitparser: ^3.1.0

dependency_overrides:
  analyzer: ^0.40.6

dev_dependencies:
  build_runner: ^1.10.4
  freezed: ^0.12.2
  test: ^1.14.3
