name: compiler
description: "ðŸ­ Compiler for the Candy language"
version: 0.1.0
homepage: https://github.com/JonasWanke/candy

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args: ^1.6.0
  basics: ^0.4.0
  collection: ^1.14.12
  dartx: ^0.5.0
  extra_pedantic: ^1.2.0
  freezed_annotation: ^0.12.0
  json_serializable: ^3.4.1
  meta: ^1.1.8
  parser:
    path: ../parser
  yaml: ^2.2.1

dev_dependencies:
  build_runner: ^1.10.4
  freezed: ^0.12.2
  json_serializable_generator: ^1.0.1
  test: ^1.14.3
